/*

=> WHEN WE CREATE WALLS CONTINUOUSLY BY DRAGGING, IT DOES'NT RERENDER

=> WHEN RELOCATE THE START NODE, IT RERENDERS EVERYTIME



=> KEY FOR ALGORITHM
bfs - Breadth first search
dijkstra - Dijkstra's Algorithm

*/